version: "3.9"

services:
  app:
    build: .
    container_name: marketing_planner_app
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    container_name: marketing_planner_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: marketing_agent
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  mysql_data: